import type { WorkExperience } from '@/types/Work';

export const workData: Array<WorkExperience> = [
  {
    id: 'mccormick-2025',
    year: '2025-Present',
    role: 'Full-Stack Software Engineer',
    company: 'McCormick & Company',
    description: "Lead McCormick's new AI Development team.",
    tech: [
      'React',
      'TypeScript',
      'Tailwind',
      'TanStack Query',
      'TanStack Router',
      'Python',
      'FastAPI',
      'Azure',
      'OpenAI',
      'LangChain',
      'Cosmos DB',
    ],
  },
  {
    id: 'lococoder-2024',
    year: '2024-Present',
    role: 'Freelance Software Engineer',
    company: 'Lococoder Labs',
    description:
      'Top Rated Plus & Expert Vetted – Upwork (Top 1% of freelancers globally)',
    bullets: [
      'Developed 10+ custom web applications for startups and SMBs in fintech and education',
      'Led technical discovery and scoped requirements for MVPs with budgets from $5k to $50k',
      'Independently own the entire software development lifecycle—from discovery and system design to implementation, deployment, and client training',
    ],
    tech: [
      'Tanstack Query',
      'Tanstack Router',
      'React',
      'TypeScript',
      'Python',
      'FastAPI',
      'Langchain',
      'Supabase',
      'Vercel',
      'Stripe',
      'Pinecone',
      'Redis',
      'Tailwind',
      'ShadCN',
      'Clerk',
    ],
  },
  {
    id: 'colorfull-2024',
    year: '2024-2025',
    role: 'Software Engineer (Contract)',
    company: 'Colorfull - Early-stage B2C catering startup based in Austin, TX',
    description:
      'Collaborated directly with the CEO and CTO to spearhead end-to-end feature development in a fast-paced startup environment',
    bullets: [
      'Built scalable features using a modern stack: Cursor, Next.js, TypeScript, FastAPI, Firebase, Google Cloud Run and Vercel; integrated with third-party platforms including Stripe and Otter',
      'Developed a vector search engine using Pinecone to enable semantic and keyword-based food item search, improving user discovery experience',
      'Introduced Redis-based caching to reduce API response times and enhance system performance',
      'Designed and implemented a customer feedback system with weekly digest emails to restaurants, closing the loop between user experience and vendor improvement',
      'Redesigned frontend components to better follow UI/UX design principles and be mobile responsive',
      'Overhauled UI components for mobile responsiveness and adherence to modern UX best practices using Tailwind, ShadCN, Aceternity and Framer Motion',
      'Led security efforts by implementing RBAC authentication middleware using Clerk and JWTs, strengthening platform access control',
    ],
    tech: [
      'Next.js',
      'TypeScript',
      'FastAPI',
      'Firebase',
      'Google Cloud Run',
      'Vercel',
      'Stripe',
      'Pinecone',
      'Redis',
      'Tailwind',
      'ShadCN',
      'Clerk',
    ],
  },
  {
    id: 'pnc-2020',
    year: '2020-2024',
    role: 'Software Engineer',
    company: 'PNC',
    description:
      "Collaborated with PNC's SRE team to design and build internal tooling that automated and accelerated key infrastructure workflows, reducing manual intervention",
    bullets: [
      'Designed and deployed a backend system using FastAPI, MySQL, and Jinja to automate ServiceNow Change Requests, reducing manual work for 30+ developers across the org',
      'Built the backend for a centralized log query platform using Express.js, MongoDB, and the Humio API, enabling engineers to search logs without vendor-specific syntax—cutting onboarding time by dozens of hours',
      'Maintained and led backend development for a FastAPI/MySQL application with hundreds of daily users to automate synthetic monitoring in Dynatrace, dramatically simplifying infra observability setup',
      'Engineered internal tooling for WebSphere/Apache node management using Vue.js (Quasar) and FastAPI; introduced Kafka and Celery-based event-driven architecture for scalable background processing',
    ],
    tech: [
      'Python',
      'FastAPI',
      'MySQL',
      'Express.js',
      'MongoDB',
      'Vue.js',
      'Kafka',
      'Celery',
      'SQLAlchemy',
      'Dynatrace',
    ],
  },
  {
    id: 'txstate-vr-2018',
    year: '2018-2019',
    role: 'Software Engineer - Intern',
    company: 'Texas State VR Lab, San Marcos, TX',
    description:
      'Designed and implemented a virtual reality training simulation in Unity3D/C# to help train new EMS recruits in Austin, leading to a faster comprehension rate of 47% compared to the non-VR group',
    bullets: [
      'Developed an extensive gesture recognition framework for the Oculus Rift SDK that tracks player hand movement',
    ],
    tech: ['Unity3D', 'C#', 'Oculus Rift SDK'],
  },
];
